"""
Streamlit Dashboard — Intelligent Municipal Water Contamination & Infrastructure Alert System
Run locally:  streamlit run app.py
Deploy free:  push this + your data/model files to a GitHub repo, then deploy on
              share.streamlit.io (Streamlit Community Cloud) pointing at app.py
"""

import streamlit as st
import pandas as pd
import numpy as np
import json
import glob
import os
import joblib

st.set_page_config(
    page_title="Water Contamination Alert System",
    page_icon="💧",
    layout="wide",
)

# ---------------- Load data ----------------
@st.cache_data
def load_sensor_data():
    if os.path.exists("water_sensor_data.csv"):
        df = pd.read_csv("water_sensor_data.csv", parse_dates=["timestamp"])
        return df
    return None

@st.cache_data
def load_pipeline_log():
    if os.path.exists("pipeline_log.csv"):
        return pd.read_csv("pipeline_log.csv")
    return pd.DataFrame()

def load_tickets():
    tickets = []
    for path in glob.glob("ticket_*.json"):
        with open(path) as f:
            tickets.append(json.load(f))
    return pd.DataFrame(tickets)

sensor_df = load_sensor_data()
pipeline_log_df = load_pipeline_log()
tickets_df = load_tickets()

# ---------------- Header ----------------
st.title("💧 Intelligent Municipal Water Contamination & Infrastructure Alert System")
st.caption("SDG 6 — Clean Water and Sanitation | Live monitoring demo")

if sensor_df is None:
    st.error(
        "water_sensor_data.csv not found. Place it in the same folder as app.py "
        "(the file generated by your Colab notebook)."
    )
    st.stop()

# ---------------- Compute node status ----------------
latest_per_node = (
    sensor_df.sort_values("timestamp")
    .groupby("node_id")
    .tail(1)
    .reset_index(drop=True)
)
latest_per_node["status"] = np.where(
    latest_per_node["anomaly_type"] != "none", "ANOMALY", "NORMAL"
)

# ---------------- Top metrics ----------------
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Nodes", latest_per_node["node_id"].nunique())
col2.metric("Nodes with Active Anomaly", int((latest_per_node["status"] == "ANOMALY").sum()))
col3.metric("Open Tickets", 0 if tickets_df.empty else int((tickets_df["status"] == "OPEN").sum()))
col4.metric("Total Readings Processed", len(sensor_df))

st.divider()

# ---------------- Map ----------------
st.subheader("📍 Node Map — Status Overview")
map_df = latest_per_node.rename(columns={"gps_lat": "lat", "gps_lon": "lon"})
map_df["color"] = np.where(map_df["status"] == "ANOMALY", "#FF3333", "#2E7D32")

st.map(map_df, latitude="lat", longitude="lon", size=200, color="color")

status_table = latest_per_node[
    ["node_id", "status", "anomaly_type", "pH", "turbidity_NTU",
     "dissolved_oxygen_mg_L", "flow_rate_Lps", "timestamp"]
].sort_values("status", ascending=False)
st.dataframe(status_table, use_container_width=True, hide_index=True)

st.divider()

# ---------------- Per-node time series ----------------
st.subheader("📈 Sensor Trends by Node")
selected_node = st.selectbox("Select a node", sorted(sensor_df["node_id"].unique()))
node_data = sensor_df[sensor_df["node_id"] == selected_node].sort_values("timestamp")

tab1, tab2, tab3, tab4 = st.tabs(["pH", "Turbidity", "Dissolved Oxygen", "Flow Rate"])
with tab1:
    st.line_chart(node_data.set_index("timestamp")["pH"])
with tab2:
    st.line_chart(node_data.set_index("timestamp")["turbidity_NTU"])
with tab3:
    st.line_chart(node_data.set_index("timestamp")["dissolved_oxygen_mg_L"])
with tab4:
    st.line_chart(node_data.set_index("timestamp")["flow_rate_Lps"])

anomalies_at_node = node_data[node_data["anomaly_type"] != "none"]
if not anomalies_at_node.empty:
    st.warning(f"{len(anomalies_at_node)} anomaly reading(s) recorded for {selected_node}")
    st.dataframe(anomalies_at_node, use_container_width=True, hide_index=True)

st.divider()

# ---------------- Maintenance tickets ----------------
st.subheader("🎫 Maintenance Tickets")
if tickets_df.empty:
    st.info("No tickets generated yet. Run simulate_pipeline() in your Colab notebook first, "
            "then re-upload the generated ticket_*.json files alongside this app.")
else:
    priority_order = {"CRITICAL": 0, "HIGH": 1}
    tickets_df["_sort"] = tickets_df["priority"].map(priority_order).fillna(2)
    display_tickets = tickets_df.sort_values("_sort").drop(columns="_sort")
    st.dataframe(
        display_tickets[["ticket_id", "priority", "node_id", "anomaly_type", "status", "timestamp"]],
        use_container_width=True,
        hide_index=True,
    )

st.divider()

# ---------------- Recent alerts / pipeline log ----------------
st.subheader("🚨 Recent Automated Actions")
if pipeline_log_df.empty:
    st.info("No pipeline log found. Upload pipeline_log.csv from your Colab run alongside this app.")
else:
    recent_anomalies = pipeline_log_df[pipeline_log_df["is_anomaly"] == True].tail(10)
    if recent_anomalies.empty:
        st.write("No anomalies triggered in the last pipeline run.")
    else:
        for _, row in recent_anomalies[::-1].iterrows():
            st.write(
                f"**{row['node_id']}** — {row['anomaly_type'].upper()} "
                f"(confidence {row['confidence_score']}) → shutdown signal sent, "
                f"ticket generated, alert dispatched."
            )

st.caption("Demo system using simulated IoT data. Not connected to real infrastructure.")
